### ISSUE TITLE
搭建出现的问题

### ISSUE THREAD

**Issue by mynameisliang** [ddssingsong/webrtc_server_node#2]
你好，我的只能显示本地的画面，不能显示对方的画面。而且火狐控制台报：ICE failed, your TURN server appears to be broken, see about:webrtc for more details和TypeError: Either sdpMid or sdpMLineIndex must be specified的错误，我的实在局域网中搭建的，没有设置外网ip

**Comment by ddssingsong** [comment]
I will close
