### ISSUE TITLE
为什么 localhost:3000 能访问，内网ip:3000 会报错

### ISSUE THREAD

**Issue by xRuby** [ddssingsong/webrtc_server_node#5]
<img width="1050" alt="屏幕快照 2019-07-31 下午2 24 04" src="https://user-images.githubusercontent.com/11939075/62188479-25641a00-b39f-11e9-9da0-994c636295ce.png">

@ddssingsong

**Comment by xRuby** [comment]
在线等，急

**Comment by xRuby** [comment]
<img width="1050" alt="屏幕快照 2019-07-31 下午2 24 04" src="https://user-images.githubusercontent.com/11939075/62188433-f6e63f00-b39e-11e9-9145-ca9c826c3168.png">

@ddssingsong

**Comment by ddssingsong** [comment]
非localhost需要配置hettps和wss，chrome浏览器规定

**Comment by xRuby** [comment]
O(∩_∩)O谢谢

**Comment by qinyang1018** [comment]
@xRuby   您好  我遇见了同样的问题  请问你是怎么解决的呢？
